// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnV1yXxEtKw8R9npxiofGQ6PcYCPW2KPo',
    appId: '1:964110836736:android:fbdccbe9157748e27064e5',
    messagingSenderId: '964110836736',
    projectId: 'mekinaye-3069b',
    storageBucket: 'mekinaye-3069b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEr7KBmZtUK3fCLlF3EWV32jNXyaGAHPY',
    appId: '1:964110836736:ios:125367e41095e72a7064e5',
    messagingSenderId: '964110836736',
    projectId: 'mekinaye-3069b',
    storageBucket: 'mekinaye-3069b.appspot.com',
    iosClientId: '964110836736-m4c77m2bnhmc1qdvep8gavjekr6ajh4p.apps.googleusercontent.com',
    iosBundleId: 'com.mekinaye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEr7KBmZtUK3fCLlF3EWV32jNXyaGAHPY',
    appId: '1:964110836736:ios:125367e41095e72a7064e5',
    messagingSenderId: '964110836736',
    projectId: 'mekinaye-3069b',
    storageBucket: 'mekinaye-3069b.appspot.com',
    iosClientId: '964110836736-m4c77m2bnhmc1qdvep8gavjekr6ajh4p.apps.googleusercontent.com',
    iosBundleId: 'com.mekinaye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZugXgzrKC_fYpX9D6kkB8Fi1jZee7xPo',
    appId: '1:964110836736:web:f1a40b2c985469487064e5',
    messagingSenderId: '964110836736',
    projectId: 'mekinaye-3069b',
    authDomain: 'mekinaye-3069b.firebaseapp.com',
    storageBucket: 'mekinaye-3069b.appspot.com',
  );

}